const products = [
  {
    id: "01",
    name: "Balanceado Premium para Perros",
    description: "Alimento completo para perros adultos de todas las razas",
    stock: 25,
    price: 18990,
    category: "perros-alimento",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "02",
    name: "Shampoo Hipoalergénico",
    description: "Shampoo suave para piel sensible de perros y gatos",
    stock: 18,
    price: 7990,
    category: "higiene",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "03",
    name: "Juguete Cuerda Resistente",
    description: "Juguete para morder y tirar, ideal para perros medianos",
    stock: 40,
    price: 4990,
    category: "juguetes",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "04",
    name: "Arenero para Gatos",
    description: "Bandeja sanitaria con borde alto anti-derrame",
    stock: 12,
    price: 12990,
    category: "gatos-accesorios",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "05",
    name: "Correa Reflectiva",
    description:
      "Correa ajustable con material reflectivo para paseos nocturnos",
    stock: 30,
    price: 6990,
    category: "perros-accesorios",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "06",
    name: "Pelota de Goma Chillona",
    description: "Juguete resistente con sonido para llamar la atención del perro",
    stock: 50,
    price: 3500,
    category: "juguetes",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "07",
    name: "Rascador para Gatos multinivel",
    description: "Estructura con sisal y plataformas para el descanso felino",
    stock: 8,
    price: 45900,
    category: "gatos-accesorios",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "08",
    name: "Cucha Acolchada Mediana",
    description: "Cama ultra suave para perros de tamaño mediano",
    stock: 15,
    price: 22000,
    category: "perros-accesorios",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "09",
    name: "Cepillo para pelo largo",
    description: "Accesorio para desenredar y remover pelo muerto sin tirones",
    stock: 25,
    price: 5200,
    category: "higiene",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "10",
    name: "Bocaditos Saludables Perro",
    description: "Snacks nutritivos sabor carne con vitaminas añadidas",
    stock: 60,
    price: 2800,
    category: "perros-alimento",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "11",
    name: "Pretal Ergonómico",
    description: "Pechera ajustable que evita la presión en el cuello",
    stock: 20,
    price: 15400,
    category: "perros-accesorios",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "12",
    name: "Fuente de Agua para Gatos",
    description: "Fuente con filtro para mantener el agua fresca y circulando",
    stock: 10,
    price: 32000,
    category: "gatos-accesorios",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "13",
    name: "Hueso de Nylon para masticar",
    description: "Hueso de larga duración para calmar la ansiedad",
    stock: 35,
    price: 4900,
    category: "juguetes",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "14",
    name: "Pipeta Antipulgas",
    description: "Tratamiento efectivo contra parásitos externos",
    stock: 100,
    price: 8500,
    category: "higiene",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "15",
    name: "Comedero Doble Acero",
    description: "Set de platos de acero inoxidable con base antideslizante",
    stock: 12,
    price: 18900,
    category: "perros-accesorios",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "16",
    name: "Collar Anti-Ahogo Gato",
    description: "Collar con broche de seguridad que se abre ante tirones fuertes",
    stock: 45,
    price: 3200,
    category: "gatos-accesorios",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "17",
    name: "Rascador de Cartón Corrugado",
    description: "Superficie para rascar que incluye catnip para mayor atracción",
    stock: 30,
    price: 4500,
    category: "juguetes",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "18",
    name: "Bebedero Portátil para Viajes",
    description: "Botella con recipiente integrado para hidratar a tu mascota en el paseo",
    stock: 22,
    price: 9800,
    category: "perros-accesorios",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "19",
    name: "Perfume para Mascotas Vainilla",
    description: "Fragancia suave y duradera que elimina malos olores sin irritar",
    stock: 18,
    price: 6500,
    category: "higiene",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "20",
    name: "Snack Dental Perro Grande",
    description: "Hueso masticable que ayuda a reducir la placa y el sarro",
    stock: 50,
    price: 4200,
    category: "perros-alimento",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "21",
    name: "Hamaca de Ventana para Gato",
    description: "Cama que se adhiere al vidrio para que tu gato disfrute del sol",
    stock: 5,
    price: 28900,
    category: "gatos-accesorios",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "22",
    name: "Juguete Peluche Kong",
    description: "Peluche ultra resistente con texturas variadas para morder",
    stock: 15,
    price: 12600,
    category: "juguetes",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "23",
    name: "Paños Absorbentes Entrenadores",
    description: "Pack de 30 unidades para educar a cachorros a hacer sus necesidades",
    stock: 40,
    price: 15900,
    category: "higiene",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "24",
    name: "Kit Dental Cepillo y Pasta",
    description: "Set para la higiene bucal con sabor a pollo para facilitar el cepillado",
    stock: 20,
    price: 7400,
    category: "higiene",
    img: "https://placedog.net/500/500?random",
  },
  {
    id: "25",
    name: "Bolso de Transporte Traslúcido",
    description: "Mochila con visor panorámico para pasear a tu gato con seguridad",
    stock: 7,
    price: 38500,
    category: "gatos-accesorios",
    img: "https://placedog.net/500/500?random",
  },
];

let error = false;

export const getProducts = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (error) {
        reject("Hubo un error, intente más tarde");
      } else {
        resolve(products);
      }
    }, 2000);
  });
};
