const products = [
  {
    id: "01",
    name: "Balanceado Premium para Perros",
    description: "Alimento completo para perros adultos de todas las razas",
    stock: 25,
    price: 18990,
    category: "perros-alimento",
    img: "https://media.istockphoto.com/id/1132075944/photo/dog-food-bag-packages-design-3d-rendering.jpg?s=2048x2048&w=is&k=20&c=mLcJHuFIG3kBrMfWnrpT752tSFZ9GdOdQk3ODx1hgMc=",
  },
  {
    id: "02",
    name: "Shampoo Hipoalergénico",
    description: "Shampoo suave para piel sensible de perros y gatos",
    stock: 18,
    price: 7990,
    category: "perros-higiene",
    img: "https://media.istockphoto.com/id/1433506264/vector/cosmetic-for-pets-shampoo-and-spray-for-dog-and-puppy-illustration-vector.jpg?s=2048x2048&w=is&k=20&c=bt7cDruepq-Xpkhzrf1Ft6Ss73XAjGh5WeFDqvlzles=",
  },
  {
    id: "03",
    name: "Juguete Cuerda Resistente",
    description: "Juguete para morder y tirar, ideal para perros medianos",
    stock: 40,
    price: 4990,
    category: "perros-juguetes",
    img: "https://media.istockphoto.com/id/116568510/photo/chewable-dog-toy-rope.jpg?s=2048x2048&w=is&k=20&c=G7unBOmGzoxmcJFKtxF484JL3tsNT3VRNb3CvB8t5UI=",
  },
  {
    id: "04",
    name: "Arenero para Gatos",
    description: "Bandeja sanitaria con borde alto anti-derrame",
    stock: 12,
    price: 12990,
    category: "gatos-accesorios",
    img: "https://media.istockphoto.com/id/1383192919/photo/blue-cat-litter-tray-isolated-on-white-with-grey-litter-and-a-scoop.jpg?s=2048x2048&w=is&k=20&c=LrBfpBc2ahgDdIgO3UBRANYIFUjW7KpUmDD_G6AM8lo=",
  },
  {
    id: "05",
    name: "Correa Reflectiva",
    description:
      "Correa ajustable con material reflectivo para paseos nocturnos",
    stock: 30,
    price: 6990,
    category: "perros-accesorios",
    img: "https://media.istockphoto.com/id/507903186/photo/lasso-orange-and-black-isolated-on-white-background.jpg?s=2048x2048&w=is&k=20&c=NuD7oH-Fs8ZA7-ZtXc438gBqCjaRkb0sALglskaVCTc=",
  },
  {
    id: "06",
    name: "Pelota de Goma Chillona",
    description: "Juguete resistente con sonido para llamar la atención del perro",
    stock: 50,
    price: 3500,
    category: "perros-juguetes",
    img: "https://media.istockphoto.com/id/2206209353/photo/massage-ball.jpg?s=2048x2048&w=is&k=20&c=EBxottSr-M3TV4fODIdS6ED1aYGQP6wizjmS8QRDHes=",
  },
  {
    id: "07",
    name: "Rascador para Gatos multinivel",
    description: "Estructura con sisal y plataformas para el descanso felino",
    stock: 8,
    price: 45900,
    category: "gatos-accesorios",
    img: "https://media.istockphoto.com/id/1137367536/photo/scratch-post-isolated.jpg?s=2048x2048&w=is&k=20&c=ZYjV8S8oxoiE55WF3kEdFmXs1f8FTr2d4tkQ0JwMEgw=",
  },
  {
    id: "08",
    name: "Cucha Acolchada Mediana",
    description: "Cama ultra suave para perros de tamaño mediano",
    stock: 15,
    price: 22000,
    category: "perros-accesorios",
    img: "https://media.istockphoto.com/id/488640434/photo/pet-bed.jpg?s=2048x2048&w=is&k=20&c=VGUsf3MuJdMhkofdffLjO5YjfozUz5m7_gOQLHm_yVg=",
  },
  {
    id: "09",
    name: "Cepillo para pelo largo",
    description: "Accesorio para desenredar y remover pelo muerto sin tirones",
    stock: 25,
    price: 5200,
    category: "gatos-higiene",
    img: "https://media.istockphoto.com/id/471058010/photo/pet-grooming-brush.jpg?s=2048x2048&w=is&k=20&c=SwRuzLw8aWw67OqK9BddLgLbqkouRXJFfZUdfustj2I=",
  },
  {
    id: "10",
    name: "Bocaditos Saludables Perro",
    description: "Snacks nutritivos sabor carne con vitaminas añadidas",
    stock: 60,
    price: 2800,
    category: "perros-alimento",
    img: "https://media.istockphoto.com/id/1473825736/vector/dog-food-packaging-design-illustration-vector.jpg?s=2048x2048&w=is&k=20&c=ra7soUQzVi9mwXJ9mbHZs52Dda7qpUaQjyEnof5cp8Y=",
  },
  {
    id: "11",
    name: "Pretal Ergonómico",
    description: "Pechera ajustable que evita la presión en el cuello",
    stock: 20,
    price: 15400,
    category: "perros-accesorios",
    img: "https://media.istockphoto.com/id/1084840294/photo/pet-harness-isolated-on-white-background-pet-accessories-concept.jpg?s=2048x2048&w=is&k=20&c=Um4ehpR9fArMMpE-raXQjvWPEKSyDUxC83z4PfuvRUk=",
  },
  {
    id: "12",
    name: "Fuente de Agua para Gatos",
    description: "Fuente con filtro para mantener el agua fresca y circulando",
    stock: 10,
    price: 32000,
    category: "gatos-accesorios",
    img: "https://media.istockphoto.com/id/1061642872/photo/thirsty-tabby-cat-drinking-water-from-a-pet-drinking-fountain-side-view-with-copy-space.jpg?s=2048x2048&w=is&k=20&c=-gLudQE9_5LaW26kt6bNgeWOV78uiSgbjG6JTToB5ks=",
  },
  {
    id: "13",
    name: "Hueso de Nylon para masticar",
    description: "Hueso de larga duración para calmar la ansiedad",
    stock: 35,
    price: 4900,
    category: "perros-juguetes",
    img: "https://media.istockphoto.com/id/2187096992/photo/red-rubber-dog-bone.jpg?s=2048x2048&w=is&k=20&c=pfq1YvdSkdz42g90IK4a1RYK13aYi03gejN4aRQ9szE=",
  },
  {
    id: "14",
    name: "Pipeta Antipulgas",
    description: "Tratamiento efectivo contra parásitos externos",
    stock: 100,
    price: 8500,
    category: "perros-higiene",
    img: "https://media.istockphoto.com/id/2153005813/photo/cosmetic-products-and-lice-comb-isolated-on-white-background.jpg?s=2048x2048&w=is&k=20&c=-YBQPVn_7d-jRVmd2KYuV5JHKmniXzmrENor529B7dE=",
  },
  {
    id: "15",
    name: "Comedero Doble Acero",
    description: "Set de platos de acero inoxidable con base antideslizante",
    stock: 12,
    price: 18900,
    category: "perros-accesorios",
    img: "https://media.istockphoto.com/id/1144230301/photo/double-pet-bowl-side-view-3d.jpg?s=2048x2048&w=is&k=20&c=p3svAPCXxnLZoISBP-zUwDX1m6FljeYIjrJ1TBZPlc4=",
  },
  {
    id: "16",
    name: "Collar Gato",
    description: "Collar de gato",
    stock: 45,
    price: 3200,
    category: "gatos-accesorios",
    img: "https://media.istockphoto.com/id/1199865571/photo/pink-cat-collar-on-white.jpg?s=2048x2048&w=is&k=20&c=LlqikasDI-O71LNo14Oi8ZXx4KBk3geiUwDeotr_XS8=",
  },
  {
    id: "17",
    name: "Rascador de Cartón Corrugado",
    description: "Superficie para rascar que incluye catnip para mayor atracción",
    stock: 30,
    price: 4500,
    category: "gatos-juguetes",
    img: "https://media.istockphoto.com/id/1683240547/photo/cat-cardboard-scratcher.jpg?s=2048x2048&w=is&k=20&c=az6irlhG4T0IxS_yDipC6Swmaq3BKokI_pkE7NgPiC4=",
  },
  {
    id: "18",
    name: "Bebedero Portátil para Viajes",
    description: "Botella con recipiente integrado para hidratar a tu mascota en el paseo",
    stock: 22,
    price: 9800,
    category: "perros-accesorios",
    img: "https://media.istockphoto.com/id/1356698824/photo/set-of-bottles-for-dogs-to-drink-water-outside-on-white-background-multicolored-bottles-from.jpg?s=2048x2048&w=is&k=20&c=vAeV-k7mqfIduE1dCUtYXcOUjAbJSwyCXNLyAYRxPsQ=",
  },
  {
    id: "19",
    name: "Perfume para Mascotas Vainilla",
    description: "Fragancia suave y duradera que elimina malos olores sin irritar",
    stock: 18,
    price: 6500,
    category: "perros-higiene",
    img: "https://media.istockphoto.com/id/1446262943/vector/transparent-bottle-mockup-with-different-labels.jpg?s=2048x2048&w=is&k=20&c=pb-uS9JbGhnDrMQ61oNgzXzb4j8CWdF08pwrSR4R-9k=",
  },
  {
    id: "20",
    name: "Snack Dental Perro Grande",
    description: "Hueso masticable que ayuda a reducir la placa y el sarro",
    stock: 50,
    price: 4200,
    category: "perros-alimento",
    img: "https://media.istockphoto.com/id/2202884877/photo/dogs-dental-sticks-white-background.jpg?s=2048x2048&w=is&k=20&c=v_rVOa3Zz5YddEpuwYcDJ3BcAFrbaliT5zhgSs28Km8=",
  },
  {
    id: "21",
    name: "Hamaca de Ventana para Gato",
    description: "Cama que se adhiere al vidrio para que tu gato disfrute del sol",
    stock: 5,
    price: 28900,
    category: "gatos-accesorios",
    img: "https://media.istockphoto.com/id/1503923434/photo/domestic-cat-looks-out-the-window-sitting-in-a-hammock.jpg?s=2048x2048&w=is&k=20&c=w3Tm0MeeEdvYvL6yqpTGev5LuLyne5AuyBb5Vb2btpA=",
  },
  {
    id: "22",
    name: "Juguete Peluche Kong",
    description: "Peluche ultra resistente con texturas variadas para morder",
    stock: 15,
    price: 12600,
    category: "perros-juguetes",
    img: "https://media.istockphoto.com/id/490787018/photo/colorful-doll-and-toys-collection-isolated-on-white-background.jpg?s=2048x2048&w=is&k=20&c=2ZpZGUeIZPD5PX7cm7hNl8ON-R4StQ7IK58NGBLNxjk=",
  },
  {
    id: "23",
    name: "Paños Absorbentes Entrenadores",
    description: "Pack de 30 unidades para educar a cachorros a hacer sus necesidades",
    stock: 40,
    price: 15900,
    category: "perros-higiene",
    img: "https://media.istockphoto.com/id/1369385638/photo/puppy-dog-sitting-on-a-pee-disposables-pad-training-isolated-on-white-background.jpg?s=2048x2048&w=is&k=20&c=EabfUuep9UbL_yDGzkr-2T5T1I9Na2zuRUU5VMkremA=",
  },
  {
    id: "24",
    name: "Kit Dental Cepillo y Pasta",
    description: "Set para la higiene bucal con sabor a pollo para facilitar el cepillado",
    stock: 20,
    price: 7400,
    category: "perros-higiene",
    img: "https://media.istockphoto.com/id/459953371/photo/toothbrush-for-pets-isolated-on-white.jpg?s=2048x2048&w=is&k=20&c=78pVi382fWixZDjSvGjT7J9EhfkowKnCB6kKcgvVO6g=",
  },
  {
    id: "25",
    name: "Bolso de Transporte Traslúcido",
    description: "Mochila con visor panorámico para pasear a tu gato con seguridad",
    stock: 7,
    price: 38500,
    category: "gatos-accesorios",
    img: "https://media.istockphoto.com/id/1300655413/photo/funny-yellow-backpack-with-a-transparent-window-porthole-for-walking-and-carrying-cats.jpg?s=2048x2048&w=is&k=20&c=leN15Tzkdk05y2dqE0dpluLVJ9OZAUWsxGx-ecSFB44=",
  },
  {
    id: "26",
    name: "Balanceado Premium para Gatos",
    description: "Alimento completo y balanceado para gatos adultos",
    stock: 25,
    price: 15990,
    category: "gatos-alimento",
    img: "https://media.istockphoto.com/id/1144230301/photo/double-pet-bowl-side-view-3d.jpg?s=2048x2048&w=is&k=20&c=p3svAPCXxnLZoISBP-zUwDX1m6FljeYIjrJ1TBZPlc4=",
  },
];

let error = false;

export const getProducts = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (error) {
        reject("Hubo un error, intente más tarde");
      } else {
        resolve(products);
      }
    }, 2000);
  });
};
